repos:
-   repo: local
    hooks:
    -   id: django-check
        name: Django check
        entry: poetry run poe check
        pass_filenames: false
        language: system
        stages:
            - push
    -   id: black
        name: Autoformatter
        entry: poetry run poe black
        pass_filenames: false
        language: system
        stages:
            - commit
            - push
    -   id: ruff
        name: Lint
        entry: poetry run poe lint
        pass_filenames: false
        language: system
        stages:
            - commit
            - push
