services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: meme_generator_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: POSTGRES
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8000:8080"
    volumes:
      - ./schema.yaml:/schema.yaml
    environment:
      SWAGGER_JSON: /schema.yaml

volumes:
  postgres_data:
